export const SET_VALUE = 'SET_VALUE'
export const SET_HISTORY = 'SET_HISTORY'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const SET_DISPLAY = 'SET_DISPLAY'
export const SET_OPERATION = 'SET_OPERATION'
export const SET_INITVALUE = 'SET_INITVALUE'
export const SET_THEME = 'SET_THEME'
